### ISSUE TITLE
SCP 914 classchange causes error

### ISSUE THREAD

**Issue by leo-ishere** [ExMod-Team/Common-Utils#2]
**Describe the bug**
SCP 914 classchange causes error when going inside 914 and setting it to what the classchange is set up to

**To Reproduce**
1. Setup classchange to anything
2. Use 914 on setup setting

**Expected behavior**
For my class to be changed

**Actual behavior**
Error in console and no class change

**Copy of the relevant CU config section**
 ```
scp914_class_changes:
    Rough:
    - original: ClassD
      new: 'SCP-049-2'
      chance: 100
      keep_inventory: true
      keep_health: false
    - original: Scientist
      new: 'SCP-049-2'
      chance: 100
      keep_inventory: true
      keep_health: true
```

**EXILED Version ("latest" is not a version):**
For example 8.14.0

**Screenshot of the results of the `plym show` command in server console:**
![image](https://github.com/user-attachments/assets/7072c573-2411-4e35-9beb-53e3c2c33d49)

**Additional context**
N/A

**Comment by sys-leo** [comment]
Updated to 7.2.3,
did not fix

**Comment by Mikihero** [comment]
error
```
[ERROR] [Exiled.Events] Method "OnUpgradingPlayer" of the class "Common_Utilities.EventHandlers.MapHandlers" caused an exception when handling the event "Exiled.Events.Features.Event`1[[Exiled.Events.EventArgs.Scp914.UpgradingPlayerEventArgs, Exiled.Events, Version=8.14.0.0, Culture=neutral, PublicKeyToken=null]]"
                                 System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
                                   at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00013] in <75633565436c42f0a6426b33f0132ade>:0
                                   at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x0004a] in <75633565436c42f0a6426b33f0132ade>:0
                                   at Common_Utilities.EventHandlers.MapHandlers.OnUpgradingPlayer (Exiled.Events.EventArgs.Scp914.UpgradingPlayerEventArgs ev) [0x0026d] in <17e96c16a5274e04b11d6ea6c2e5d552>:0
                                   at Exiled.Events.Features.Event`1[T].InvokeNormal (T arg) [0x00028] in <bfb010202e6c42e582ef2d13d23749f1>:0
```

**Comment by Mikihero** [comment]
the issue you're facing is actually because you used the wrong name for 049-2:
```
scp914_class_changes:
  Rough:
  - original: 'ClassD'
    new: 'Scp0492'
    chance: 100
    keep_inventory: true
    keep_health: false
  - original: 'Scientist'
    new: 'Scp0492'
    chance: 100
    keep_inventory: true
    keep_health: true
```
